#!/bin/bash
echo "Personlize script running...."
echo "Installing yarn"
sudo npm install -g yarn

export NEEDRESTART_MODE=a
export DEBIAN_FRONTEND=noninteractive

echo "Upgrading packages"
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get update -y
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get upgrade -y

echo "Installing MySQL stuff"
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get install -y libmysqlclient21 libmysqlclient-dev

echo "Installing protoc"
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get install -y protoc-gen-go

echo "Installing additional tools"
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get install -y net-tools atop

echo "Installing PostGRES"
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get install -y postgresql postgresql-client

git config --global pager.branch false

/opt/goenv/shims/go env -w GOPRIVATE="github.com/lacework-dev/*"

# used for vuln jira connector work
echo "Install NGrok"
sudo  snap install ngrok

echo "Install hurl"
cargo install hurl


# echo "Installing Neo4J"
#curl -fsSL https://debian.neo4j.com/neotechnology.gpg.key |sudo gpg --dearmor -o /usr/share/keyrings/neo4j.gpg
#echo "deb [signed-by=/usr/share/keyrings/neo4j.gpg] https://debian.neo4j.com stable 4.1" | sudo tee -a /etc/apt/sources.list.d/neo4j.list
#DEBIAN_FRONTEND=noninteractive sudo add-apt-repository ppa:cleishm/neo4j -y
#DEBIAN_FRONTEND=noninteractive sudo apt-get install neo4j-client libneo4j-client-dev -y
