#!/usr/bin/bash
echo "Personalize script running...."
echo "Installing yarn"
sudo npm install -g yarn

export NEEDRESTART_MODE=a
export DEBIAN_FRONTEND=noninteractive

echo "Upgrading packages"
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get update -y
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get upgrade -y

echo "Installing MySQL stuff"
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get install -y libmysqlclient21 libmysqlclient-dev

echo "Installing protoc"
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get install -y protoc-gen-go

echo "Installing additional tools"
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get install -y net-tools atop

echo "Installing PostGRES"
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get install -y postgresql postgresql-client

echo "Installing Hyperscan"
NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive sudo apt-get install -y libhyperscan-dev

git config --global pager.branch false

/opt/goenv/shims/go env -w GOPRIVATE="github.com/lacework-dev/*"

# used for vuln jira connector work
echo "Install NGrok"
sudo  snap install ngrok

echo "Install hurl"
/opt/cargo/bin/cargo install hurl


# echo "Installing Neo4J"
wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
echo 'deb https://debian.neo4j.com stable 4.4' | sudo tee /etc/apt/sources.list.d/neo4j.list
sudo apt-get update
DEBIAN_FRONTEND=noninteractive sudo apt-get install neo4j-client libneo4j-client-dev -y
